

import type { Metadata } from "next";
import { geistMono, geistSans } from "../app/config/fonts";
import "./globals.css";

import QueryClientProviderWrapper from "@/components/layout/QueryClientProviderWrapper";


export const metadata: Metadata = {
  title: "Create Next ",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        

        <QueryClientProviderWrapper>{children}</QueryClientProviderWrapper>

       
        
     
        
       
      </body>
    </html>
  );
}
